FROM node:lts-buster
RUN git clone https://github.com/kashmiricrasher/KASHMIRI-MD /auth_info_baileys/xIKRATOSx
WORKDIR /auth_info_baileys/xIKRATOSx
RUN npm install && npm install -g pm2 || yarn install --network-concurrency 1
COPY . .
EXPOSE 9090
CMD ["npm", "start"]